# -*- coding: utf-8 -*-
"""1,2,3더하기.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YLvVjhJHbvkUcctAPyvW7H8MDV6THASf
"""

def go(goal, sm):
  global arr,cnt
  
  if goal == sm:
    cnt += 1
    return 0
  
  elif sm > goal:
    return 0  
  
  for x in range(len(arr)):
    go(goal, sm+arr[x])
  
################################
  
arr = [1,2,3]

for i in range(int(input())):
  cnt = 0
  result = int(input())
  go(result, 0)
  print(cnt)