# -*- coding: utf-8 -*-
"""날짜계산.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1l2n4F8ycMrklqtQVPT2Ex4Oo-3dx4EfP
"""

e,s,m = map(int,input().split())

years = 1
E=1
S=1
M=1

while (e!=E or s!=S or m!=M):
  E += 1
  S += 1
  M += 1
  years += 1
  
  if E == 16:
    E = 1
  if S == 29:
    S = 1
  if M == 20:
    M =1
print(years)