# -*- coding: utf-8 -*-
"""로또.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CDXtpAcVR8vz4rVyYNNfcdDAeKeuD5gh
"""

finale = []

def Lotto(a, idx, cnt):  
  global n
  
  if cnt == 6:    
    print(' '.join(finale))
    return 0 
  
  elif idx == n:
  
    return 0
  
  finale.append(str(a[idx]))
#  print('#append', finale,'인덱스 :',idx,'카운트 :',cnt)

  Lotto(a, idx+1, cnt+1)
  
  finale.pop()
# print('#pop', finale,'인덱스 :',idx,'카운트 :',cnt)

  Lotto(a, idx+1, cnt)
#  print(finale,'인덱스 :',idx,'카운트 :',cnt)

while  True:
  
  lst = list(map(int, input().split()))
  if lst[0] == 0:
    break
  n, num = int(lst[0]), lst[1:]
  Lotto(num, 0, 0)
  print( )