# -*- coding: utf-8 -*-
"""일곱난쟁이.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Tgp1DUtkmRvOyP45ccfcVFOG495knb2B
"""

test = []
for x in range(9):
  test.append(int(input()))

sums =sum(test)  

for i in range(len(test)):
  for k in range(i):
    if sums - test[i] - test[k] == 100:
      test.pop(i)
      test.pop(k)
      test = sorted(test)
      for z in range(len(test)):
        print(test[z])
      break
  if len(test) <=7 :
    break