# -*- coding: utf-8 -*-
"""초콜릿자르기.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LeW3i64WyWIny8KX27hhnw_vv54-dzLz
"""

k = list(map(int,input().split()))
print(k[0]* k[1] -1)