# -*- coding: utf-8 -*-
"""한수.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BA-Km7Dm9ISDjGercbz2Tq-2PD0b-yex
"""

maxes = input()
cnt = 0
for i in range(1,int(maxes)+1):
  test = list(map(int, str(i)))
  
  if i < 100: 
    cnt +=1
    
  else:
    k = test[0] - test[1]
    for j in range(1, len(test)-1):
      if test[j]-test[j+1] != k:
        break
      else:
        cnt += 1
print(cnt)