# -*- coding: utf-8 -*-
"""알고스팟.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1I1GxAbfhLa2ziTY-MBfCMzoVeF2PjvuB
"""

from collections import deque

q= deque()

열, 행= map(int, input().split())
path = [[]*열 for _ in range(행)]
visited = [[False]*열 for j in range(행)]
cnt =  [[0]*열 for k in range(행)]

dx = [1,-1,0,0]
dy = [0,0,1,-1]

for i in range(행):
  path[i] = list(map(int, input()))

visited[0][0] = True
q.append((0,0))

while q:
  x,y = q.popleft()
  
  for z in range(4):
    nx, ny = x+dx[z], y+dy[z]
    
    if path[x][y] ==0 and 0 <= nx < 행 and 0 <= ny < 열:
      if path[nx][ny] == 0 and visited[nx][ny] == False:
        visited[nx][ny] = True
        cnt[nx][ny] = cnt[x][y] 
        q.appendleft((nx,ny))

      if path[nx][ny] == 1 and visited[nx][ny] == False:
        visited[nx][ny] = True
        cnt[nx][ny] = cnt[x][y] +1
        q.append((nx,ny))

    if path[x][y] == 1 and 0 <= nx < 행 and 0 <= ny < 열:      
      if path[nx][ny] == 0 and visited[nx][ny] == False:
        visited[nx][ny] = True
        cnt[nx][ny] = cnt[x][y]
        q.appendleft((nx,ny))

      if path[nx][ny] == 1 and visited[nx][ny] == False:
        visited[nx][ny] = True
        cnt[nx][ny] = cnt[x][y] +1 
        q.append((nx,ny))

print(cnt[행-1][열-1])
